on: { push: { branches: ['**'] }, release: { types: [published] } }
jobs:
  foxplug:
    runs-on: ubuntu-latest
    steps:
      - { uses: OsakaSaul/foxplug-changelog-action@v1, with: { foxplug-token: "${{ secrets.FOXPLUG_TOKEN }}" } }
